// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8xtIpRZ-jMknvqb989b-0awP7zpd6oIM',
    appId: '1:23267778597:web:bdd44bf4f172f5dfd4dfcc',
    messagingSenderId: '23267778597',
    projectId: 'tea-diary-app',
    authDomain: 'tea-diary-app.firebaseapp.com',
    storageBucket: 'tea-diary-app.firebasestorage.app',
    measurementId: 'G-84D0KHGSJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD3TXbgQ0ZZZ5yFvw0PK68Yd0PR3-rbj4',
    appId: '1:23267778597:android:b5d95ac0162f9a98d4dfcc',
    messagingSenderId: '23267778597',
    projectId: 'tea-diary-app',
    storageBucket: 'tea-diary-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8xtIpRZ-jMknvqb989b-0awP7zpd6oIM',
    appId: '1:23267778597:web:dcd57e3c062143f0d4dfcc',
    messagingSenderId: '23267778597',
    projectId: 'tea-diary-app',
    authDomain: 'tea-diary-app.firebaseapp.com',
    storageBucket: 'tea-diary-app.firebasestorage.app',
    measurementId: 'G-L9YXYCNX3N',
  );

}